scm:
  enabled: true
  kind: github
  env_token: UPDATECLI_GITHUB_TOKEN
  owner: "rancher-sandbox"
  repository: "rancher-ecp-qa"
  #username: "updatecli[bot]"
  #user: "updatecli[bot]"
  #email: updatecli[bot]@users.noreply.github.com
  branch: main
  commitusingapi: true
  labels:
    - "dependencies"
    - "updatecli"
  commitmessage:
    footers: "Signed-off-by: Tomas Hehejik <thehejik@suse.com>"
