name: Lint

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  cypress-lint:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: current
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm
        run: |
          npm install --save-dev
          npm ls --depth=0

      - name: Analysis
        run: |
          npm run lint
